# Generated by Django 5.1.4 on 2025-01-13 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_author",
            field=models.BooleanField(default=False, verbose_name="وضعیت نویسندگی"),
        ),
        migrations.AddField(
            model_name="user",
            name="special_user",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name=" کاربر ویژه تا"
            ),
        ),
    ]
