# Generated by Django 5.1.4 on 2025-01-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(
                to="blog.category", verbose_name="دسته\u200cبندی"
            ),
        ),
    ]
