# Generated by Django 5.1.4 on 2025-01-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_category_options_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_special",
            field=models.BooleanField(default=False, verbose_name="مقاله ویژه"),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("d", "پیشنویس"),
                    ("p", "منتشر شده"),
                    ("i", " درحال بررسی"),
                    ("b", " برگشت داده شده"),
                ],
                max_length=1,
                verbose_name="وضعیت",
            ),
        ),
    ]
