# Generated by Django 5.1.4 on 2025-01-20 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_article_is_special_alter_article_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="آدرس آی\u200cپی"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.article"
                    ),
                ),
                (
                    "ip_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.ipaddress"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="hits",
            field=models.ManyToManyField(
                blank=True,
                related_name="hits",
                through="blog.ArticleHit",
                to="blog.ipaddress",
                verbose_name="بازدیدها",
            ),
        ),
    ]
